---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: example-es-cluster
spec:
  kibana: {}
  cerebro: {}
  client-node-replicas: 1
  master-node-replicas: 1
  data-node-replicas: 1
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 1G
  java-options: "-Xms512m -Xmx512m"
  volumeMounts:
    - name: elk-persistent-storage
      mountPath: /data
  snapshot:
    scheduler-enabled: false
    bucket-name: elasticsnapshots99
    cron-schedule: "@every 2m"
volumes:
  - name: elk-persistent-storage
    persistentVolumeClaim:
      claimName: claim-elk